/*
** EPITECH PROJECT, 2019
** <project name>
** File description:
** animtypes.c -- No description
*/

#include "entities/entities.h"

const animtype_t DUCK_ANIMTYPES[ANIM_DUCK_COUNT] = {
    [ANIM_DUCK_HORIZONTAL_RIGHT] = ANIM_TYPE_PING_PONG,
    [ANIM_DUCK_HORIZONTAL_LEFT] = ANIM_TYPE_PING_PONG,
    [ANIM_DUCK_DIAGONAL_RIGHT] = ANIM_TYPE_PING_PONG,
    [ANIM_DUCK_DIAGONAL_LEFT] = ANIM_TYPE_PING_PONG,
    [ANIM_DUCK_VERTICAL_DOWN] = ANIM_TYPE_PING_PONG,
    [ANIM_DUCK_VERTICAL_UP] = ANIM_TYPE_PING_PONG,
    [ANIM_DUCK_DEATH] = ANIM_TYPE_ONCE,
};
